
sbatch_skeleton <- function() {
  return(
"#!/bin/bash
#################
#set a job name  
#SBATCH --job-name=JOBNAME
#################  
#a file for job output, you can check job progress
#SBATCH --output=OUTFILE
#################
# a file for errors from the job
#SBATCH --error=ERRORFILE
#################
#time you think you need; default is one hour
#SBATCH --time=JOBTIME
#################
#quality of service; think of it as job priority
#SBATCH --qos=QUALITY
#################
#number of nodes you are requesting
#SBATCH --nodes=NODENUMBER
#################
#memory per node; default is 4000 MB
#SBATCH --mem=MEMPERNODE
#you could use --mem-per-cpu; they mean what we are calling cores
#################
#get emailed about job BEGIN, END, and FAIL
#SBATCH --mail-type=MAILTYPE
#################
#who to send email to; please change to your email
#SBATCH  --mail-user=USER_EMAIL
#################
#task to run per node; each node has 16 cores
#SBATCH --ntasks=TASKS_PER_NODE
#################
#SBATCH --cpus-per-task=CPUS_PER_TASK
#now run normal batch commands

ml load R/3.2.2
ml load pandoc/1.19.2
srun R -f PATH_TO_R_SCRIPT ARGS_TO_R_SCRIPT"
)}

# in above, just changed from module load R/3.0.2



generateSbatch <- function(sbatch_params, runfile_path = NA, run_now = F) {
  
  #sbatch_params is a data frame with the following columns
  #jobname: string, specifies name associated with job in SLURM queue
  #outfile: string, specifies the name of the output file generated by job
  #errorfile: string, specifies the name of the error file generated by job
  #jobtime: string in hh:mm:ss format, max (maybe soft) is 48:00:00 
  #specifies the amoung of time job resources should be allocated
  #jobs still running after this amount of time will be aborted
  #quality: kind of like priority, normal works
  #node_number, integer: the number of nodes (computers w/16 cpus each) to allocate 
  #mem_per_node, integer: RAM, in MB, to allocate to each node
  #mailtype, string: ALL, BEGIN, END, FAIL: what types of events should you be notified about via email
  #user_email string: email address: email address to send notifications
  #tasks_per_node: integer, number of tasks, you should probably use 1
  #cpus_per_task: integer, 1-16, number of cpus to use, corresponds to number of available cores per task
  #path_to_r_script: path to r script on sherlock
  #args_to_r_script: arguments to pass to r script on command line
  #write_path: where to write the sbatch file
  #server_sbatch_path: where sbatch files will be stored on sherlock
  #runfile_path is a string containing a path at which to write an R script that can be used to run
  #the batch files generated by this function. 
  #if NA, no runfile will be written
  #run_now is a boolean specifying whether batch files should be run as they are generated
  
  sbatches <- list()
  if (!is.na(runfile_path)) {
    outfile_lines <- c(paste0("# Generated on ",  Sys.time()))
  }
  for (sbatch in 1:nrow(sbatch_params) ) {
    gen_batch <- sbatch_skeleton()
    #set job name
    if (is.null(sbatch_params$jobname[sbatch])) { 
      gen_batch <- gsub("JOBNAME", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("JOBNAME", sbatch_params$jobname[sbatch], gen_batch) 
    }
    #set outfile name
    if (is.null(sbatch_params$outfile[sbatch])) { 
      gen_batch <- gsub("OUTFILE", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("OUTFILE", sbatch_params$outfile[sbatch], gen_batch) 
    }
    #set errorfile name
    if (is.null(sbatch_params$errorfile[sbatch])) { 
      gen_batch <- gsub("ERRORFILE", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("ERRORFILE", sbatch_params$errorfile[sbatch], gen_batch) 
    }
    #set jobtime
    if (is.null(sbatch_params$jobtime[sbatch])) { 
      gen_batch <- gsub("JOBTIME", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("JOBTIME", sbatch_params$jobtime[sbatch], gen_batch) 
    }
    #set quality
    if (is.null(sbatch_params$quality[sbatch])) { 
      gen_batch <- gsub("QUALITY", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("QUALITY", sbatch_params$quality[sbatch], gen_batch) 
    }
    #set number of nodes
    if (is.null(sbatch_params$node_number[sbatch])) { 
      gen_batch <- gsub("NODENUMBER", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("NODENUMBER", sbatch_params$node_number[sbatch], gen_batch) 
    }
    #set memory per node
    if (is.null(sbatch_params$mem_per_node[sbatch])) { 
      gen_batch <- gsub("MEMPERNODE", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("MEMPERNODE", sbatch_params$mem_per_node[sbatch], gen_batch) 
    }
    #set requested mail message types
    if (is.null(sbatch_params$mailtype[sbatch])) { 
      gen_batch <- gsub("MAILTYPE", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("MAILTYPE", sbatch_params$mailtype[sbatch], gen_batch) 
    }
    #set email at which to receive messages
    if (is.null(sbatch_params$user_email[sbatch])) { 
      gen_batch <- gsub("USER_EMAIL", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("USER_EMAIL", sbatch_params$user_email[sbatch], gen_batch) 
    }
    #set tasks per node
    if (is.null(sbatch_params$tasks_per_node[sbatch])) { 
      gen_batch <- gsub("TASKS_PER_NODE", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("TASKS_PER_NODE", sbatch_params$tasks_per_node[sbatch], gen_batch) 
    }
    #set cpus per task
    if (is.null(sbatch_params$cpus_per_task[sbatch])) { 
      gen_batch <- gsub("CPUS_PER_TASK", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("CPUS_PER_TASK", sbatch_params$cpus_per_task[sbatch], gen_batch) 
    }
    #set path to r script
    if (is.null(sbatch_params$path_to_r_script[sbatch])) { 
      gen_batch <- gsub("PATH_TO_R_SCRIPT", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("PATH_TO_R_SCRIPT", sbatch_params$path_to_r_script[sbatch], gen_batch) 
    }
    #set args to r script
    if (is.null(sbatch_params$args_to_r_script[sbatch])) { 
      gen_batch <- gsub("ARGS_TO_R_SCRIPT", "unnamed", gen_batch) 
    } else { 
      gen_batch <- gsub("ARGS_TO_R_SCRIPT", sbatch_params$args_to_r_script[sbatch], gen_batch) 
    }
    
    #write batch file
    if (is.null(sbatch_params$write_path[sbatch])) { 
      cat(gen_batch, file = paste0("~/sbatch_generated_at_", gsub(" |:|-", "_", Sys.time()) ), append = F)
    } else { 
      cat(gen_batch, file = sbatch_params$write_path[sbatch], append = F)
    }
    
    if (!is.na(sbatch_params$server_sbatch_path[sbatch])) {
      outfile_lines <- c(outfile_lines, paste0("system(\"sbatch ", sbatch_params$server_sbatch_path[sbatch], "\")"))
    } 
    sbatches[[sbatch]] <- gen_batch
  }
  if (!is.na(runfile_path)) {
    cat(paste0(outfile_lines, collapse = "\n"), file = runfile_path)
  }
  if(run_now) { system(paste0("R -f ", runfile_path)) } 
  
  return(sbatches)
}

args = commandArgs(trailingOnly = TRUE)
print(args)

# n.Reps (number of datasets that each worker should generate)
n.files  = as.numeric(args[1]) 

# n (number of subjects) 
n.subj = as.numeric(args[2])

# obs (number of observations per subject)
n.obs = as.numeric(args[3])

# betas file
.betas = args[4]

# survival file
.surv = args[5]

# censoring times file
.cens = args[6]

# simulation file
.sim_folder = args[7]


#sbatch_params = data.frame(row)
#sbatch_params[2:n.files,] = row

# EDIT THIS LINE EACH TIME
.sim_folder_path <- paste("/share/PI/manishad/power/",.sim_folder, sep = "")
setwd(.sim_folder_path)
path = .sim_folder_path

#jobname = paste("job", 1:n.files, sep="_")
#outfile = paste("rm_", 1:n.files, ".out", sep="")
#errorfile = paste("rm_", 1:n.files, ".err", sep="")
#write_path = paste(path, "/sbatch_files/", 1:n.files, ".sbatch", sep="")

jobname = "job_1"
outfile = paste("rm_1", ".out", sep="")
errorfile = paste("rm_1", ".err", sep="")
write_path = paste(path, "/sbatch_files/", "1.sbatch", sep="")
runfile_path = ""

# COVARIATES SBATCHES
sbatch_params <- data.frame(jobname,
                            outfile,
                            errorfile,
                            jobtime = "1:30:00",
                            quality = "normal",
                            node_number = 1,
                            mem_per_node = 64000,
                            mailtype =  "ALL",
                            user_email = "ariadnag@stanford.edu",
                            tasks_per_node = 1,
                            cpus_per_task = 1,
                            path_to_r_script = "/share/PI/manishad/power/simulate.R",
                            args_to_r_script = paste("--args 1 ", jobname, " " ,n.subj, " ", n.obs, " 1 '",.sim_folder,"'" ,sep=""),
                            write_path,
                            stringsAsFactors = F,
                            server_sbatch_path = NA)

generateSbatch(sbatch_params, runfile_path)

# OUTCOME SBATCHES 

jobname2 = paste("job_out", 1:n.files, sep="_")
outfile = paste("rm_out_", 1:n.files, ".out", sep="")
errorfile = paste("rm_out_", 1:n.files, ".err", sep="")
write_path = paste(path, "/sbatch_files/", 1:n.files, "_out.sbatch", sep="")
runfile_path = "" 
n = paste( 1:n.files, sep="" )


sbatch_params2 <- data.frame(jobname2,
                             outfile,
                             errorfile,
                             jobtime = "1:30:00",
                             quality = "normal",
                             node_number = 1,
                             mem_per_node = 64000,
                             mailtype =  "ALL",
                             user_email = "ariadnag@stanford.edu",
                             tasks_per_node = 1,
                             cpus_per_task = 1,
                             path_to_r_script = "/share/PI/manishad/power/simulateCEROutcome.R",
                             args_to_r_script = paste("--args 1 ", jobname2, " " ,"'./datasets/",jobname,"_dataset_1'" ," '", .betas, "' '", .surv, "' '", .cens, "' ",.sim_folder, " ",n ,sep=""),
                             write_path,
                             stringsAsFactors = F,
                             server_sbatch_path = NA)
  

generateSbatch(sbatch_params2, runfile_path)

# FIT THE MODEL SBATCHES 

jobname3 = paste("job_fit", 1:n.files, sep="_")
outfile = paste("rm_fit_", 1:n.files, ".out", sep="")
errorfile = paste("rm_fit_", 1:n.files, ".err", sep="")
write_path = paste(path, "/sbatch_files/", 1:n.files, "_fit.sbatch", sep="")
runfile_path = "" 


sbatch_params3 <- data.frame(jobname3,
                             outfile,
                             errorfile,
                             jobtime = "1:30:00",
                             quality = "normal",
                             node_number = 1,
                             mem_per_node = 64000,
                             mailtype =  "ALL",
                             user_email = "ariadnag@stanford.edu",
                             tasks_per_node = 1,
                             cpus_per_task = 1,
                             path_to_r_script = "/share/PI/manishad/power/fitCoxMEModel.R",
                             args_to_r_script = paste("--args 1 ", " " ,"'",jobname2,"_outcome'" ," ",jobname3,"_results.csv ",.sim_folder, sep=""),
                             write_path,
                             stringsAsFactors = F,
                             server_sbatch_path = NA)


generateSbatch(sbatch_params3, runfile_path)


# RESULTS SBATCH 
jobname = "job_results_1"
outfile = paste("rm_res_1", ".out", sep="")
errorfile = paste("rm_res_1", ".err", sep="")
write_path = paste(path, "/sbatch_files/", "results.sbatch", sep="")
runfile_path = ""

sbatch_params4 <- data.frame(jobname,
                            outfile,
                            errorfile,
                            jobtime = "1:30:00",
                            quality = "normal",
                            node_number = 1,
                            mem_per_node = 64000,
                            mailtype =  "ALL",
                            user_email = "ariadnag@stanford.edu",
                            tasks_per_node = 1,
                            cpus_per_task = 1,
                            path_to_r_script = "/share/PI/manishad/power/parseResultsSherlock.R",
                            args_to_r_script = paste("--args '",.sim_folder,"'" ,sep=""),
                            write_path,
                            stringsAsFactors = F,
                            server_sbatch_path = NA)

generateSbatch(sbatch_params4, runfile_path)


# RUN THEM ALL
setwd( paste(path, "/sbatch_files", sep="") )

result_dependencies <- ""

all_batches <- "#! /bin/bash \n"
all_batches <- paste(all_batches,"RES=$(sbatch -p manishad ",.sim_folder_path,"/sbatch_files/1.sbatch)\n", sep ="")
for (i in 1:n.files) {
  all_batches <- paste(all_batches,"RES2=$(sbatch --dependency=afterok:${RES##* } -p manishad ",.sim_folder_path,"/sbatch_files/", i, "_out.sbatch) \n", sep="")
  all_batches <-  paste(all_batches, "FIT",i,"=$(sbatch --dependency=afterok:${RES2##* } -p manishad ",.sim_folder_path,"/sbatch_files/", i, "_fit.sbatch) \n", sep="")
  
  #create variable so results are not parsed until all the results finish running
  result_dependencies <- paste(result_dependencies, ":${FIT",i,"##* }", sep = "")
}
 all_batches <-  paste(all_batches, "sbatch --dependency=afterok",result_dependencies," -p manishad ",.sim_folder_path,"/sbatch_files/results.sbatch \n", sep="")

write(
  x = all_batches
  , file= "all_batches.sbatch"
)

system(paste("sbatch -p manishad ",.sim_folder_path,"/sbatch_files/all_batches.sbatch", sep = ""))

#system(paste("RES=$(sbatch -p manishad ",.sim_folder_path,"/sbatch_files/1.sbatch)", sep =""))


